# -*- coding: utf-8 -*-
"""error high image resolution yolo custom training for help

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AImyB25NCd_Tl2Jrm7TvB9df5KEb7FBu
"""

!git clone https://github.com/pjreddie/darknet

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/darknet

!nvidia-smi

!make

!./darknet

# Commented out IPython magic to ensure Python compatibility.
# %cp -r "/content/drive/MyDrive/yolophd.zip" "/content/darknet/pcbdata"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/darknet/pcbdata/

!unzip yolophd.zip

# Commented out IPython magic to ensure Python compatibility.
# %cp -r  /content/darknet/pcbdata/yolopcbdefects/*txt /content/darknet/datapcb/

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

!python processin.py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/darknet

!./darknet detector train cfg/voc.data /content/darknet/cfg/yolov3.cfg /content/darknet/yolov3.weights

!wget https://pjreddie.com/media/files/yolov3.weights